helpdesk/app/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('ticket/<int:id>', views.ticket, name='ticket'),
    path('edit-ticket/<int:id>', views.editticket, name='editticket'),
]

helpdesk/helpdesk/urls.py
from django.contrib import admin
from django.urls import path, include
from register import views as register_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', register_views.register, name='register'),
    path('', include("app.urls")),
    path('', include("django.contrib.auth.urls"))

]

helpdesk/app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Ticket(models.Model):
    STATUS_CHOICES = [
        ('draft', 'Draft'),
        ('complete', 'Complete'),
        ('inProgress', 'In Progress'),
    ]
    
    PRIORITY_CHOICES = [
        ('low', 'Low'),
        ('medium', 'Medium'),
        ('high', 'High'),
    ]
    client = models.ForeignKey(User, on_delete=models.CASCADE, related_name='client', blank=True, null=True)
    assignedStaff = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, related_name='assignedStaff')
    title = models.CharField(max_length=100)
    description = models.TextField()
    priority = models.CharField(max_length=20, choices=PRIORITY_CHOICES, default='low')
    date = models.DateTimeField()
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='draft')
    def __str__(self):
        return self.title
    
    
class TicketComment(models.Model):
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE)
    comment = models.TextField()
    date = models.DateTimeField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        return self.comment

helpdesk/register/models.py
from django.db import models

# Create your models here.

helpdesk/app/forms.py
from django import forms
from datetime import datetime

class TicketInitialForm(forms.Form):
    title = forms.CharField(label="Title", max_length=200, widget=forms.TextInput(attrs={'placeholder': 'How can we help you?'}))
    description = ""
    date = datetime.now()
    priority = ""
    closed = False
    
class TicketDetailForm(forms.Form):
    title = forms.CharField(label="Title", max_length=200)
    description = forms.CharField(widget=forms.Textarea)
    date = datetime.now()
    priority = forms.ChoiceField(label="Priority", choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")])
    closed = False
    
class CommentForm(forms.Form):
    comment = forms.CharField(label="Leave a comment", max_length=350, widget=forms.Textarea)
    date = datetime.now()
    ticket = ""

helpdesk/register/forms.py
from django import forms
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):
    email = forms.EmailField()
    
    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

helpdesk/app/views.py
from datetime import datetime
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponseRedirect
from .models import Ticket
from .forms import CommentForm, TicketDetailForm, TicketInitialForm
from django.contrib.auth.decorators import login_required
# Create your views here.

@login_required(login_url='/login/')
def index(response):
    tickets = Ticket.objects.filter(client=response.user).order_by('-date')
    if response.method == "POST":
        form = TicketInitialForm(response.POST)
        if form.is_valid():
            n = form.cleaned_data["title"]
            d = ""
            p = "low"
            u = response.user
            t = Ticket(title=n, description=d, priority=p, date=datetime.now() ,client=u)
            t.save()
            # Redirect to editticket view with the ID of the newly created ticket
            return redirect(reverse('editticket', args=[t.id]))
    else:
        form = TicketInitialForm()
        return render(response, "app/home.html", {"tickets": tickets, "form": form})

@login_required(login_url='/login/')
def ticket(response, id):
    ticket = Ticket.objects.get(id=id)
    if response.method == "POST":
        form = CommentForm(response.POST)
        if form.is_valid():
            c = form.cleaned_data["comment"]
            d = datetime.now()
            t = Ticket.objects.get(id=id)
            u = response.user
            t.ticketcomment_set.create(comment=c, date=d, user=u)
            t.save()
            form = CommentForm()
            return HttpResponseRedirect(reverse('ticket', kwargs={"id": id}), {"ticket": ticket, "form": form})
    else:
        form = CommentForm()
        return render(response, "app/ticket.html", {"ticket": ticket, "form": form})

@login_required(login_url='/login/')
def editticket(response, id):
    ticket = Ticket.objects.get(id=id)
    if response.method == "POST":
        if ticket.status == "draft":
            form = TicketDetailForm(response.POST)
            if form.is_valid():
                n = form.cleaned_data["title"]
                d = form.cleaned_data["description"]
                p = form.cleaned_data["priority"]
                t = Ticket.objects.get(id=id)
                t.title = n
                t.description = d
                t.priority = p
                t.status = "inProgress"
                t.save()
                form = TicketDetailForm()
                return redirect('/')

        else:
            print("Ticket is not a draft. Cannot edit.")
    else:
        form = TicketDetailForm(initial={"title": ticket.title, "description": ticket.description, "priority": ticket.priority})
        
    return render(response, "app/editticket.html", {"ticket": ticket, "form": form})

helpdesk/register/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm

# Create your views here.
def register (response):
    if response.method == "POST":
        form = RegisterForm(response.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
    
    form = RegisterForm()
    return render(response, "register/register.html", {"form": form})

helpdesk/app/templates/app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <style>
      .nav img {
        height: 32px;
      }
    </style>
    {% block head %} {% endblock %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    <title>{% block title %}Help Desk{% endblock %}</title>
  </head>
  <body class="vh-100 bg-light">
    <nav class="bg-white p-2">
      <div class="nav container d-flex justify-content-between align-items-center">
        <a href="/" class="fs-2 text-secondary text fw-bolder">Help<span class="text-info">Desk</span></a>
        <a class="btn" href="/admin">Admin Panel</a>
      </div>
    </nav>
    <div class="container mh-100 mt-5" id="content">
      {% block content %} {% endblock %}
    </div>
  </body>
</html>

helpdesk/app/templates/app/editticket.html
{% extends 'app/base.html' %}
{% load crispy_forms_tags %}
{% block head %}
<style>
    form p {
        display: flex;
        flex-direction: column;
    }
</style>
{% endblock %}
{% block title %}
Help Desk - Edit Ticket
{% endblock %}
{% block content %}
<h1 class="text-center">#{{ticket.id}} - {{ticket.title}}</h1>
<div class="row justify-content-md-center">
    <form class="col-sm-12 col-md-8 col-lg-6" method="post">
        {% csrf_token %} {{ form|crispy }}   <button class="btn btn-dark" type="submit" name="save">Create Ticket</button>
    </form>
</div>
{% endblock %}

```

helpdesk/app/templates/app/home.html
{% extends 'app/base.html' %} {% load static %} {% block title %} Help Desk -
Home {% endblock %} {% block head %}
<style>
  label {
    display: none !important;
  }
  button {
    border: none;
    background: none;
  }

  p {
    margin-bottom: 0 !important;
  }

  form {
    display: flex;
    align-items: center;
    border-radius: 6px;
    border: 1px solid black;
    height: 40px;
  }

  .ticket-card {
    display: flex;
    align-items: center;
    border-radius: 6px;
    border: 1px solid black;
    height: 40px;
  }

  #id_title {
    width: 100%;
    height: 100%;
    padding: 0 8px;
    border: none;
    background: none;
    font-size: 16px;
    font-weight: 300;
    background-color: white;
    border-radius: 6px;
  }

  #id_title:placeholder {
    color: #bababa;
  }

  .draft {
    border-color: #bababa;
  }

  .inProgress {
    border-color: #ff9900;
  }

  .complete {
    border-color: #35cb00;
  }

  .status-text {
    font-size: 12px;
    font-weight: 600;
    letter-spacing: -0.5px;
  }

  .draft-text {
    color: #bababa;
  }

  .inProgress-text {
    color: #ff9900;
  }

  .complete-text {
    color: #35cb00;
  }

  .status-ball {
    height: 10px;
    width: 10px;
    border-radius: 50vh;
  }

  .draft-fill {
    background-color: #bababa;
  }

  .inProgress-fill {
    background-color: #ff9900;
  }

  .complete-fill {
    background-color: #35cb00;
  }
  form p {
    margin-bottom: 0 !important;
    width: 100%;
    height: 100%;
  }
  .max-height {
    height:100vh;
    max-height: 100vh;
  }

  .shadow-effect:hover {
    box-shadow: 0 .5rem 1rem rgba(0,0,0,.15)!important;
  }

</style>
{% endblock %} {% block content %}
<div class="max-height row justify-content-md-center">
  <div class="col-sm-12 col-md-8 col-lg-6 pb-5">
    <h2 class="fs-4 tight pb-2">Open a Ticket</h2>
    <form autocomplete="off" method="post">
      {% csrf_token %} {{form.as_p}}
      <button type="submit" name="save">
        <img alt="search icon" src="https://fonts.gstatic.com/s/i/materialiconsoutlined/arrow_forward/v1/24px.svg" />
      </button>
    </form>
  </div>

  <div class="overflow-auto col-sm-12 col-lg-8">
    <h2 class="fs-4 tight font-weight-light pb-2">My Tickets</h2>
    {%for ticket in tickets%}
    <a
      href="{% if ticket.status == 'draft' %}{% url 'editticket' ticket.id %}{% else %}{% url 'ticket' ticket.id %}{% endif %}"
      class="{{ ticket.status }} shadow-effect bg-white text-decoration-none px-3 py-4 ticket-card mb-2 fw-light d-flex justify-content-between align-items-center"
    >
      <div class="d-flex gap-2">
        <p class="fw-bold">#{{ticket.id}}</p>
        <p class="m-0">{{ticket.title}}</p>
      </div>  
      <div class="d-flex align-items-center gap-1">
        <p class="status-text {{ ticket.status|add:'-text' }}">{{ticket.get_status_display}}</p>
        <div class="status-ball {{ ticket.status|add:'-fill' }}"></div>
      </div>
    </a>
    {%endfor%}
  </div>
</div>
{% endblock %}

helpdesk/app/templates/app/ticket.html
{% extends 'app/base.html' %} {% load crispy_forms_tags %} {% block title %}
Help Desk - View Ticket {% endblock %}
{% load static %}
{% block head %}
<style>
  #div_id_comment .form-control {
    height: 100px;
  }
</style>
{% endblock %} {% block content %}
<div class="row gap-4 mh-100">
  <div class="col bg-white p-4 rounded">
    <h1 class="fs-3">Ticket Information</h1>
    <hr />
    <p class="pt-2 m-0"><b>Ticket Title:</b> {{ticket.title}}</p>
    <p class="m-0"><b>Ticket Priority:</b> {{ticket.priority}}</p>
    <p class="pb-2"><b>Assigned Technician:</b> 
      {% if ticket.assignedStaff %}
        {{ ticket.assignedStaff.first_name }} {{ ticket.assignedStaff.last_name }}
      {% else %}
        N/A
      {% endif %}
    </p>
    
    <p><b>Ticket Description:</b> {{ticket.description}}</p>
  </div>
  <div class="mh-100 col bg-white p-4 rounded">
    <div class="border-bottom">
      <h1 class="fs-3">Comments <span class="fw-light">({{ticket.ticketcomment_set.all.count}})</span></h1>
    </div>
    {% for ticketComment in ticket.ticketcomment_set.all %}
    <div class="mh-100 overflow-scroll row p-3 border-bottom">
      <div class="col-1">
        <img class="img-fluid" alt="user icon" src="https://fonts.gstatic.com/s/i/materialiconsoutlined/person/v1/24px.svg" />
      </div>
      <div class="col">
        <div class="d-flex gap-1">
          <p class="m-0 fw-bold">{{ticketComment.user.first_name}} {{ticketComment.user.last_name}} - </p>
          <p class="m-0">{{ticketComment.date}}</p>
        </div>
        <div>
          <p class="m-0">{{ticketComment.comment}}</p>
        </div>
      </div>
    </div>
    {% endfor %}
    <form class="pt-3 w-100 col-sm-12 col-md-8 col-lg-6" method="post">
      {% csrf_token %} {{ form|crispy }}
      <button class="btn btn-dark" type="submit" name="save">Comment</button>
    </form>
  </div>
</div>
{% endblock %}

helpdesk/register/templates/register/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block head %} {% endblock %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    <title>{% block title %}Help Desk{% endblock %}</title>
  </head>
  <body>
    <div class="container h-full" id="content">
      {% block content %} {% endblock %}
    </div>
  </body>
</html>

helpdesk/register/templates/register/register.html
{% extends "register/base.html" %}
{% block title %}Help Desk - Create Account{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<div class="row justify-content-md-center">
    <div class="pt-5 col-sm-12 col-md-8 col-lg-6">
    <form method="post" class="form-group">
        {% csrf_token %} {{ form|crispy }}
        <button type="submit" class="btn btn-success">Register</button>
    </form>
</div>
</div>
{% endblock %}